# Generated by Django 4.2.9 on 2026-02-20 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Box Cricket Turf', help_text='Name of the venue', max_length=200)),
                ('has_seating', models.BooleanField(default=True, help_text='Seating area available')),
                ('has_lighting', models.BooleanField(default=True, help_text='Lighting facility available')),
                ('has_restrooms', models.BooleanField(default=True, help_text='Restrooms available')),
                ('has_equipments', models.BooleanField(default=True, help_text='Cricket equipments available')),
                ('has_parking', models.BooleanField(default=True, help_text='Parking facility available')),
                ('total_boxes', models.IntegerField(default=1, help_text='Total number of box-cricket turfs')),
                ('weekday_price', models.DecimalField(decimal_places=2, default=600.0, help_text='Price per hour on weekdays (Mon-Fri)', max_digits=6)),
                ('weekend_price', models.DecimalField(decimal_places=2, default=700.0, help_text='Price per hour on weekends (Sat-Sun)', max_digits=6)),
                ('advance_percentage', models.IntegerField(default=20, help_text='Advance amount percentage required for booking')),
                ('email', models.EmailField(default='vamsibilla248@gmail.com', help_text='Contact email', max_length=254)),
                ('phone', models.CharField(default='+91 7801019106', help_text='Contact phone number', max_length=20)),
                ('opening_time', models.TimeField(default='10:00:00', help_text='Opening time')),
                ('closing_time', models.TimeField(default='18:00:00', help_text='Closing time')),
                ('no_cancellation', models.BooleanField(default=True, help_text='No cancellation policy')),
                ('no_reschedule', models.BooleanField(default=True, help_text='No reschedule policy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the cricket match')),
                ('time_slot', models.CharField(choices=[('6-7', '6:00 AM - 7:00 AM'), ('7-8', '7:00 AM - 8:00 AM'), ('8-9', '8:00 AM - 9:00 AM'), ('5-6', '5:00 PM - 6:00 PM'), ('6-7pm', '6:00 PM - 7:00 PM'), ('7-8pm', '7:00 PM - 8:00 PM')], help_text='Time slot for the match', max_length=10)),
                ('cricket_type', models.CharField(choices=[('box', 'Box Cricket'), ('normal', 'Normal Cricket')], help_text='Type of cricket - Box or Normal', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=500, help_text='Price per slot', max_digits=5)),
                ('max_players', models.IntegerField(default=11, help_text='Maximum number of players')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cricket Slot',
                'verbose_name_plural': 'Cricket Slots',
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot', 'cricket_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slots.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
