# Generated by Django 4.2.9 on 2026-01-18 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the cricket match')),
                ('time_slot', models.CharField(choices=[('6-7', '6:00 AM - 7:00 AM'), ('7-8', '7:00 AM - 8:00 AM'), ('8-9', '8:00 AM - 9:00 AM'), ('5-6', '5:00 PM - 6:00 PM'), ('6-7pm', '6:00 PM - 7:00 PM'), ('7-8pm', '7:00 PM - 8:00 PM')], help_text='Time slot for the match', max_length=10)),
                ('cricket_type', models.CharField(choices=[('box', 'Box Cricket'), ('normal', 'Normal Cricket')], help_text='Type of cricket - Box or Normal', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=500, help_text='Price per slot', max_digits=5)),
                ('max_players', models.IntegerField(default=11, help_text='Maximum number of players')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cricket Slot',
                'verbose_name_plural': 'Cricket Slots',
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot', 'cricket_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slots.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
