# Generated by Django 5.2.10 on 2026-01-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Box Cricket Turf', help_text='Name of the venue', max_length=200)),
                ('has_seating', models.BooleanField(default=True, help_text='Seating area available')),
                ('has_lighting', models.BooleanField(default=True, help_text='Lighting facility available')),
                ('has_restrooms', models.BooleanField(default=True, help_text='Restrooms available')),
                ('has_equipments', models.BooleanField(default=True, help_text='Cricket equipments available')),
                ('has_parking', models.BooleanField(default=True, help_text='Parking facility available')),
                ('total_boxes', models.IntegerField(default=1, help_text='Total number of box-cricket turfs')),
                ('weekday_price', models.DecimalField(decimal_places=2, default=600.0, help_text='Price per hour on weekdays (Mon-Fri)', max_digits=6)),
                ('weekend_price', models.DecimalField(decimal_places=2, default=700.0, help_text='Price per hour on weekends (Sat-Sun)', max_digits=6)),
                ('advance_percentage', models.IntegerField(default=20, help_text='Advance amount percentage required for booking')),
                ('email', models.EmailField(default='vamsibilla248@gmail.com', help_text='Contact email', max_length=254)),
                ('phone', models.CharField(default='+91 7801019106', help_text='Contact phone number', max_length=20)),
                ('opening_time', models.TimeField(default='10:00:00', help_text='Opening time')),
                ('closing_time', models.TimeField(default='18:00:00', help_text='Closing time')),
                ('no_cancellation', models.BooleanField(default=True, help_text='No cancellation policy')),
                ('no_reschedule', models.BooleanField(default=True, help_text='No reschedule policy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
    ]
